# Objective:
# Learn NumPy for fast numerical computation
# Apply it on bhavcopy data to calculate returns and volatility

In [1]:
import numpy as np
import pandas as pd

In [8]:
arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


In [ ]:
prices = [100, 102, 101, 105] # it is a list of closing prices for 4 days
np_prices = np.array(prices) # it converts the list of prices into a numpy array

In [11]:
returns = (np_prices[1:] - np_prices[:-1]) / np_prices[:-1]
returns

array([ 0.02      , -0.00980392,  0.03960396])

In [14]:
arr + 10
arr * 2
arr / 2
arr

array([1, 2, 3, 4])

In [15]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr1 + arr2

array([5, 7, 9])

In [ ]:
np.mean(arr)
  

np.float64(2.5)

In [20]:
print(np.max(arr))
print(np.min(arr))
print(np.std(arr))   # volatility


4
1
1.118033988749895


In [21]:
arr = np.array([10, 20, 30, 40, 50])

arr[0]      # first
arr[-1]     # last
arr[1:4]    # slice

array([20, 30, 40])

In [23]:
arr[arr > 35]

array([40, 50])

In [24]:
arr = np.array([100, 102, 101])

arr - 100

array([0, 2, 1])

In [25]:
prices = np.array([100, 102, 101, 105])

returns = (prices[1:] - prices[:-1]) / prices[:-1]
print(returns)

[ 0.02       -0.00980392  0.03960396]


In [26]:
log_returns = np.log(prices[1:] / prices[:-1])
print(log_returns) # log return is the natural logarithm of the ratio of consecutive prices. It is often used in finance because it has nice properties, such as being time-additive and more normally distributed than simple returns.

[ 0.01980263 -0.0098523   0.03883983]


In [27]:
np.std(returns) # volatility of returns

np.float64(0.020313454228698492)

In [28]:
df = pd.read_csv("../data/bhavcopy.csv")

df.head()

,SYMBOL,SERIES,DATE1,PREV_CLOSE,OPEN_PRICE,HIGH_PRICE,LOW_PRICE,LAST_PRICE,CLOSE_PRICE,AVG_PRICE,TTL_TRD_QNTY,TURNOVER_LACS,NO_OF_TRADES,DELIV_QTY,DELIV_PER
0,1018GS2026,GS,22-Apr-2026,102.98,102.79,102.99,102.79,102.99,102.99,102.98,349,0.36,11,349,100.00
1,20MICRONS,EQ,22-Apr-2026,177.43,178.14,179.58,177.10,179.24,178.38,178.38,65747,117.28,1374,34726,52.82
2,21STCENMGM,EQ,22-Apr-2026,33.71,34.31,34.38,34.31,34.38,34.38,34.36,4514,1.55,14,4514,100.00
3,360ONE,EQ,22-Apr-2026,1108.35,1114.00,1123.80,1042.00,1055.00,1054.90,1068.54,5903548,63081.65,127390,2433064,41.21
4,3BBLACKBIO,EQ,22-Apr-2026,1388.05,1399.00,1399.00,1341.05,1350.10,1355.15,1368.79,3250,44.49,507,2074,63.82
